### PR TITLE
edited deep equal exercise

### LINKED ISSUE #71: Fix deep comparison function
It looks completely broken with additional test cases

To start work on it you have to pull that one 

https://github.com/brotherhood-of-javascript/js-eng-init/commit/788f9db602b10f6b274ac25a84d5c19552068b96

### PR DESCRIPTION
**Pull request by yzhbankov**
fixed #71

### CODE REVIEW

File: 01-syntax/03-data-structures/deep-comparation/deepEqual.js [hunk 1]
```diff
@@ -8,11 +8,14 @@ function deepEqual(object_1, object_2) {
     var counter_1 = 0;
     var counter_2 = 0;
 
-    if ((typeof object_1 != 'object' && object_1 == null) &&
-        (typeof object_2 != 'object' && object_2 == null))
+    if (object_1 === object_2)
```
Comment (nesterone) [inline 01-syntax/03-data-structures/deep-comparation/deepEqual.js]: { } ?

File: 01-syntax/03-data-structures/deep-comparation/deepEqual.js [hunk 2]
```diff
@@ -8,29 +8,86 @@ function deepEqual(object_1, object_2) {
     var counter_1 = 0;
```
Comment (nesterone) [inline 01-syntax/03-data-structures/deep-comparation/deepEqual.js]: Could I ask you to use camelCase notation instead of ke_bab notation 
```
var couner1 = 0; //much better

````

File: 01-syntax/03-data-structures/deep-comparation/deepEqual.js [hunk 3]
```diff
@@ -8,29 +8,86 @@ function deepEqual(object_1, object_2) {
...
     var counter_2 = 0;
 
-    if ((typeof object_1 != 'object' && object_1 == null) &&
-        (typeof object_2 != 'object' && object_2 == null))
+    if (object_1 === object_2) {
+        return true;
+    }
+    if (typeof object_1 != 'object' || object_1 == null ||
```
Comment (nesterone) [inline 01-syntax/03-data-structures/deep-comparation/deepEqual.js]: Let's make your program a bit beautiful, 

wrap logic like 

```js

typeof object_1 != 'object' || object_1 == null

```

to something like

```js

function isObject(obj){
    //...
}

```

it would make your code more self explaining

File: 01-syntax/03-data-structures/deep-comparation/deepEqual.js [hunk 4]
```diff
@@ -8,29 +8,86 @@ function deepEqual(object_1, object_2) {
...
         counter_2++;
-        if (!(node in object_1) || !deepEqual(object_1[node], object_2[node]))
+        if (!(node in object_1) || !deepEqual(object_1[node], object_2[node])) {
+
             return false;
+        }
     }
 
-    return (counter_1 == counter_2);
+    return counter_1 == counter_2;
```
Comment (nesterone) [inline 01-syntax/03-data-structures/deep-comparation/deepEqual.js]: It makes sense to move counters check upper before actually comparison with *object_2* 
becase if obj1 has 2 props and obj2 has 3 it doesn't make sense to compare them

File: 01-syntax/03-data-structures/deep-comparation/deepEqual.js [hunk 5]
```diff
@@ -8,29 +8,86 @@ function deepEqual(object_1, object_2) {
...
+    if (typeof object_1 != 'object' || object_1 == null ||
+        typeof object_2 != 'object' || object_2 == null) {
         return false;
+    }
 
-    if (object_1 === object_2) return true;
-
-    for (var node in object_1)
-        counter_1++;
+    for (var node in object_1) counter_1++;
```
Comment (nesterone) [inline 01-syntax/03-data-structures/deep-comparation/deepEqual.js]: Maybe not a *node* but *prop* or *key* ...

File: 01-syntax/03-data-structures/deep-comparation/deepEqual.js [hunk 6]
```diff
@@ -8,29 +8,86 @@ function deepEqual(object_1, object_2) {
...
 
     for (var node in object_2) {
         counter_2++;
-        if (!(node in object_1) || !deepEqual(object_1[node], object_2[node]))
+        if (!(node in object_1) || !deepEqual(object_1[node], object_2[node])) {
```
Comment (nesterone) [inline 01-syntax/03-data-structures/deep-comparation/deepEqual.js]: Oh my mind !  It looks complicated for me ;-( 

As variant, try to split condition to two conditions
Also you may write code that 

```js
return deppEqual(.. ..)

```
